import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { Poppins } from "next/font/google";

// const poppins = Poppins({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "battle- blitz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=''>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
